
stages:
  - build
  - test
  - deploy

before_script:
  - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 830137832802.dkr.ecr.us-east-1.amazonaws.com

docker-build-web:
  image: alpine:latest
  stage: build
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --platform=linux/amd64 -t flask-app web-hit-counter/
    - docker tag flask-app:1.0 "$CI_REGISTRY_IMAGE/flask-app${tag}"
    - docker push "$CI_REGISTRY_IMAGE/flask-app${tag}"

docker-build-redis:
  image: alpine:latest
  stage: build
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --platform=linux/amd64 -t redis redis/
    - docker tag redis "$CI_REGISTRY_IMAGE/redis${tag}"
    - docker push "$CI_REGISTRY_IMAGE/redis${tag}"

variables:
  CI_REGISTRY_IMAGE: 830137832802.dkr.ecr.us-east-1.amazonaws.com

